version: "3.3"
services:
  #database
  mysql:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: toor
      MYSQL_USER: wordpress
      MYSQL_DATABASE: wordpress
      MYSQL_PASSWORD: wordpress
    restart: always
    volumes: 
      - ./db:/var/lib/mysql
    ports:
      - 3306:3306
    networks: 
      wordpress-net:
        aliases:
          - docker.network
  #phpmyadmin
  phpmyadmin:
    depends_on:
      - mysql
    image: phpmyadmin/phpmyadmin:5.0
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306
    volumes: 
      - ./php:/etc/phpmyadmin
    restart: always
    ports:
      - 8080:80
    networks: 
      wordpress-net:
        aliases: 
          - dockerfile.network
  #wordpress
  wordpress:
    depends_on:
      - mysql
    image: wordpress:5.4.0-php7.2-apache
    environment: 
      WORDPRESS_DB_HOST: mysql
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: wordpress
      WORDPRESS_DB_NAME: wordpress
    volumes:
      - ./wordpress:/var/www/html
    restart: always
    ports:
      - 80:80
    networks: 
      wordpress-net:
        aliases:
          - dockerfile.network

volumes: 
  db: 
  php: 
  wordpress: 

networks:
  wordpress-net: