version: '3'

services:
  web:
    depends_on:
      - mariadb-container
    image: paulhiv/labo:web
    ports:
      - "8080:3000"
    networks:
      - frontend

  mariadb-container:
    build: .
    ports:
      - "3306:3306"
    volumes:
      - ../docker/tp/db/:/var/lib/mysql/
    networks:
      - frontend

networks:
  frontend: 